// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23/05/2025, 18:11:57
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/doria/Desktop/myfintrack/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/doria/Desktop/myfintrack/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/doria/Desktop/myfintrack/frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/doria/Desktop/myfintrack/frontend/src/plugins/**/*.{js,ts,mjs}","C:/Users/doria/Desktop/myfintrack/frontend/src/composables/**/*.{js,ts,mjs}","C:/Users/doria/Desktop/myfintrack/frontend/src/utils/**/*.{js,ts,mjs}","C:/Users/doria/Desktop/myfintrack/frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/doria/Desktop/myfintrack/frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/doria/Desktop/myfintrack/frontend/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;