# Generated by Django 5.2.1 on 2025-05-26 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('transaction_type', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=2, verbose_name='transaction type')),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('GIFT', 'Gift'), ('OTHER_INC', 'Other Income'), ('HOUSING', 'Housing'), ('FOOD', 'Food'), ('TRANSPORT', 'Transportation'), ('HEALTH', 'Health'), ('ENTERTAIN', 'Entertainment'), ('EDUCATION', 'Education'), ('SHOPPING', 'Shopping'), ('UTILITIES', 'Utilities'), ('TRAVEL', 'Travel'), ('OTHER_EXP', 'Other Expense')], max_length=10, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
