# Generated by Django 4.2.7 on 2025-05-30 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_load_demo_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('SPENDING', 'Spending Pattern'), ('SAVINGS', 'Savings Opportunity'), ('BUDGET', 'Budget Alert'), ('GENERAL', 'General Advice')], max_length=10, verbose_name='insight type')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('data_points', models.TextField(blank=True, help_text='JSON serialized data to support the insight', null=True, verbose_name='data points')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'financial insight',
                'verbose_name_plural': 'financial insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('GIFT', 'Gift'), ('OTHER_INC', 'Other Income'), ('HOUSING', 'Housing'), ('FOOD', 'Food'), ('TRANSPORT', 'Transportation'), ('HEALTH', 'Health'), ('ENTERTAIN', 'Entertainment'), ('EDUCATION', 'Education'), ('SHOPPING', 'Shopping'), ('UTILITIES', 'Utilities'), ('TRAVEL', 'Travel'), ('OTHER_EXP', 'Other Expense')], max_length=10, verbose_name='category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10, verbose_name='period')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['category'],
                'unique_together': {('user', 'category', 'period')},
            },
        ),
    ]
